---
title: "Climate"
output: github_document
  # html_document:
  #   toc: TRUE
  #   toc_float: TRUE
  #   code_folding: hide
  #   editor_options:
  #     chunk_output_type: console
  #   dev: png
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(warning = FALSE)
knitr::opts_chunk$set(message = FALSE)
```

```{r code setup}
library(tidyverse)
library(readxl)
library(dplyr)
#Based on: https://bl.ocks.org/gka/raw/1d716deada5f05e595c77df39f7320b4/e95b47f706f295cd72fb875eae9c2b6493eab367/
```

## Read & Summarize Data
## GITHUB CHANGE TEST
```{r read & summarize}
climate <- read_csv("group-3.csv")

summary(climate)
monthstr <- as_labeller(c(`0`="January", `1` = "February",
                           `2`="March", `3`="April",
                           `4`="May", `5`="June",
                           `6`="July", `7`="August",
                           `8`="September", `9`= "OctoberR",
                           `10`="November", `11`="DecembeR"))
```

#Plot
```{r plot}

climate %>%
  ggplot(mapping = aes(x = year, y = tmp)) +
  geom_rect(data=subset(climate,month==c(0,2,4,6,8,10) ), fill="#e6e6e6",
            xmin=-Inf, xmax=Inf, ymin=-Inf, ymax=Inf, alpha=1) +
  geom_rect(data=subset(climate,month==c(1,3,5,7,9,11) ), fill="#f2f2f2",
            xmin=-Inf, xmax=Inf, ymin=-Inf, ymax=Inf, alpha=1) +
  geom_point(size = 0.05, fill = "#494949") +
  geom_smooth(method = "loess", size = 1, se = FALSE, color = '#FB00F7')+
  #geom_smooth(method = "lm", formula = y ~ 1, se = FALSE, color = "#2166AC")+ # avg_lines
  #Add curves by using provided data:
  #geom_line(mapping = aes(x = year, y = tmpLoess), 
  #           color = "#FB00F7", size = 1)+
  facet_grid(cols = vars(month), switch="x",
             labeller = monthstr) +
  theme_light() +
  scale_y_continuous(labels=function(x) paste0(x,"°C")) +
  theme(
        panel.spacing = unit(0,"lines"),
        panel.border = element_blank(),
        panel.grid.major.x = element_blank(),
        panel.grid = element_blank(),
        panel.grid.minor = element_blank(),
        panel.background = element_rect(fill = NA),
        panel.grid.major.y = element_line(color = "#dddddd", size = .5),
        panel.ontop = TRUE,
        axis.ticks = element_blank(),
        #axis.line = element_blank(),
        axis.title = element_blank(),
        axis.text.x = element_blank(),
        axis.text.y = element_text(size=6),
        strip.background = element_blank(),
        strip.text = element_text(color = 'black', size = 5))
ggsave("climategraph.png")  

```